### PR TITLE
Extending url. URL can now be a valid link or a view name.

### PR DESCRIPTION
**Pull request by patrickhusi**

### CODE REVIEW

**Comment by yakky** [comment]
Oh, this is cool, while quite technical.
Would you rebase it and add Django 1.7 migrations to this PR?

**Comment by jsma** [comment]
I'm strongly against adding 'developer only' buttons to the admin. Only developers would have any knowledge of named url patterns or dotted paths to view functions, not typical content editors. Additionally, Django 1.8 deprecated the ability to reverse Python dotted paths ("The ability to reverse() URLs using a dotted Python path will be removed" as of 1.10). It will instead require the actual view function or named url only.

**Comment by morganwahl** [comment]
My two cents: we have CMS Plugins our page-authors use to write HTML and Django Templates directly; as-such the urlnames we define are part of the API us Python developers present to them.

**Comment by FinalAngel** [comment]
@patrickhusi thank you very much and sorry for the very late response. If you still would like this feature to get added, please rebase and reopen this pr to the latest changes :)

**Pull request closed without merging**
