### PR TITLE
Split AbstractLink and create a normal models.Model class to fix #133

### LINKED ISSUE #133: Not possible to use AbstractLink as associated link in own CMSPlugin
I would like to do something like this:
```
from django.db import models
from cms.models.pluginmodel import CMSPlugin

from djangocms_link.models import AbstractLink


class FooPluginModel(CMSPlugin):
    title = models.CharField(max_length=50)

class AssociatedLink(AbstractLink):
    plugin = models.ForeignKey(FooPluginModel, related_name="links")
```

This doesn't work and raise into a error like this:
```
ValueError: 'AssociatedLink' has more than one ForeignKey to 'FooPluginModel'.
```
This raised in `django.forms.models._get_foreign_key()` with local variables like:
```
fks_to_parent=[
    <django.db.models.fields.related.ForeignKey: parent>,
    <django.db.models.fields.related.OneToOneField: cmsplugin_ptr>
]
```

The problem is IMHO that `djangocms_link.models.AbstractLink` inherit from `CMSPlugin`

Any idea how to handle this?

Think there should be a Base-Link-class that inherit only from `models.Model` ?!?

### PR DESCRIPTION
**Pull request by jedie**
to fix #133

### CODE REVIEW

**Comment by jedie** [comment]
I rebase this on current master.

**Comment by jedie** [comment]
I rebase it to current master branch

**Comment by jedie** [comment]
ping.

Is this project is alive?!?

**Comment by czpython** [comment]
Thanks for the pr.
As explained in https://github.com/divio/djangocms-link/issues/133, we would like to keep the abstract class specific to cms plugins.

**Pull request closed without merging**
