### PR TITLE
Adaptions to readme and editorconfig

### PR DESCRIPTION
**Pull request by FinalAngel**
* Fixes https://github.com/divio/djangocms-link/issues/101
* Adds editorconfig setting for newline problem on link.html file

### CODE REVIEW

**Comment by FinalAngel** [comment]
@jsma does that work for you?

**Comment by jsma** [comment]
This is a good start! I was hoping for something a bit louder, e.g. "Backwards incompatible changes in 2.0.0" like Django's release notes.  

A simple 'Backwards incompatible' note at least makes me read more closely and potentially scan the commit messages to piece together how this might impact me. 

Ideally it would also add a note about the clear consequence of the change e.g. "If you've overridden the default template, you will need to move it to the new location and ensure it uses the new template variables." etc.

Thanks!

**Comment by FinalAngel** [comment]
@jsma we sadly don't have traditional "release notes" only the changelog. Though an alarm bell should ring when switching from 1.9.x to 2.x as per semver.org it indicates backwards incompatible changes.

I'll resolve the issue then.

**Comment by czpython** [comment]
@FinalAngel As pointed out by @jsma, I think we should add the "Backwards incompatible changes" line. This is also done on the cms. The reason being that anyone reading these, without much context won't know that those are backwards incompatible and to imply that through versioning in my opinion is not good. Best to be explicit about it.

**Comment by FinalAngel** [comment]
@czpython link this?

**Pull request merged**
