### PR TITLE
Add migrations for unmigrated schema changes and test to detect such changes

### PR DESCRIPTION
**Pull request by morganwahl**
`djangocms-link` has had several releases with unmigrated schema changes, which is quite annoying for users.

This branch adds a test for such a situation that only runs on Django 1.7. An equivalent for South is problematic, since the South equivalent to `dry_run` is called `stdout`, which is also a kwarg of `call_command`.

This branch also adds migrations for some seemingly unmigrated changes currently in master.

### CODE REVIEW

**Comment by morganwahl** [comment]
Great, `EmailField`'s default max_length changes between Djagno 1.7 and 1.8.

More problematically, the output of _("mailto") changes depending on Django version and... language. Must research how this should be handled regarding migrations...

**Comment by morganwahl** [comment]
So, it turns out Django 1.7 looks at a default locale (seems to be "en", on my machine, anyway) when looking for schema changes. Django 1.8 thankfully turns off translation entirely in such circumstances.

This PR updates the 'mailto' field's `verbose_name` to be the same as it's "en" translation, so Django 1.8 doesn't detect a schema change in circumstances where Django 1.7 wouldn't.

**Comment by morganwahl** [comment]
Note: `makemessages` needs to be run on this branch. I'm not exactly sure how to do that.

**Comment by yakky** [comment]
@morganwahl Great! use ``python test_settings.py makemessages`` to update locales

**Comment by morganwahl** [comment]
.po updated

**Comment by morganwahl** [comment]
@yakky Anything blocking getting this merged? Would like avoid deploying our fork.

Thanks!

**Comment by yakky** [comment]
Sorry @morganwahl merging it now

**Comment by morganwahl** [comment]
Thanks!

**Pull request merged**
